version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - ROCKET_ENV=staging
      - REDIS_HOST=redis
      - RUST_BACKTRACE=1
    ports:
      - 8000:80
  redis:
    image: redis:alpine
